### ISSUE TITLE
粒子間の衝突計算のバグ

### ISSUE THREAD

**Issue by qoopen0815** [qoopen0815/ParticlePhysics#18]
**Describe the bug**
[SampleScene](https://github.com/qoopen0815/ParticlePhysics/tree/main/Assets/Examples/Scenes)を実行すると、窪地に堆積した砂が青矢印の方向に移動し続ける現象が起きる。その影響で堆積した砂が赤線に沿って傾いて積もってしまう。

![image](https://user-images.githubusercontent.com/26988372/212450220-42ad1b80-f9ca-4ebd-ac6a-cac71eed49c0.png)

粒子の状態をアップデートする関数（下記行）に含まれる「粒子同士の衝突計算をする行（133行目）」をコメントアウトするとこの現象が起きなくなるので粒子間の衝突計算にバグがあると考えられる。
https://github.com/qoopen0815/ParticlePhysics/blob/607dac876b5b7939551d4e06fd959d49c77a25af/Packages/ParticlePhysics/Runtime/Scripts/Solver/SandPhysicsSolver.cs#L130-L137

**To Reproduce**
1. Open [SampleScene.unity](https://github.com/qoopen0815/ParticlePhysics/tree/main/Assets/Examples/Scenes).
2. Run project.

**Expected behavior**
堆積面が水平となり、粒子も静止して堆積するのが理想です。

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
 - RAM: 32.0 GB
 - Unity: 2021.3.16f1

**Comment by Autumn60** [comment]
TerrainのHeightmapResolutionを上げることで同様の現象が起きなくなることを確認しました。

また、これはこちらの環境の問題かもしれませんが、最初にプロジェクトを開いた際にBucketのMeshのisReadableがFalseになっていてSDF(?)を作成する際にエラーが発生していました。

https://github.com/qoopen0815/ParticlePhysics/blob/dev/object-collision/Assets/Develop/Models/Bucket.fbx.meta#L35

**Comment by qoopen0815** [comment]
@Autumn60 さん、こちらもトライありがとうございます。
https://github.com/qoopen0815/ParticlePhysics/pull/20 の修正によりTerrainResolutionを上げなくてもちゃんと動作するようになりました！

元々の実装だと「頂点の法線ベクトル」を使っていたので、TerrainResolutionを上げることでバグが解消したように見えたのかなと思います。
- TerrainResolutionが小さい（いびつな形状）⇒頂点の法線ベクトル≠面の法線ベクトル
- TerrainResolutionが大きい（滑らかな形状）⇒頂点の法線ベクトル≒面の法線ベクトル

PRの修正で「面の法線ベクトル」をTerrainの衝突計算で使えるようになりましたので、結果的にTerrainResolutionを元に戻してもちゃんと動くようになったのかな！と考えてます。（違ったら指摘お願いします笑）

**Comment by qoopen0815** [comment]
https://twitter.com/QooPen0815/status/1612396145556459522?s=20

このときの挙動も今ならすごく納得がいきます。。。

**Comment by qoopen0815** [comment]
本件解決したのでcloseします。
@Autumn60 さんありがとうございました！また宜しくお願い致します🙌
